version: '2'

services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_CUSTOM_LDIF_DIR=/ldifs

    volumes:
      - 'openldap_data:/bitnami/openldap'
      - ./ex9.ldif:/ldifs/ex9.ldif
volumes:
  openldap_data:
    driver: local
